// Test generated by RoostGPT for test uploadfilespringboot using AI Type Vertex AI and AI Model code-bison

package com.bootexample4.products.controller;

import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.ResponseEntity;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class ProductController_deleteProduct_dcaff736d4_Test {

    @InjectMocks
    private ProductController productController;

    @Mock
    private ProductRepository productRepository;

    @Test
    public void shouldReturn200WhenProductExists() {
        // given
        Long id = 1L;
        Product product = new Product();
        product.setId(id);
        when(productRepository.findById(id)).thenReturn(Optional.of(product));

        // when
        ResponseEntity<Object> responseEntity = productController.deleteProduct(id);

        // then
        assertEquals(ResponseEntity.ok().build(), responseEntity);
    }

    @Test
    public void shouldReturn404WhenProductDoesNotExist() {
        // given
        Long id = 1L;
        when(productRepository.findById(id)).thenReturn(Optional.empty());

        // when
        ResponseEntity<Object> responseEntity = productController.deleteProduct(id);

        // then
        assertEquals(ResponseEntity.notFound().build(), responseEntity);
    }
}
