// Test generated by RoostGPT for test uploadfilespringboot using AI Type Vertex AI and AI Model code-bison

package com.bootexample4.products.controller;

import com.bootexample4.products.model.Product;
import com.bootexample4.products.repository.ProductRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.ResponseEntity;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
@AutoConfigureMockMvc
public class ProductController_getAllProducts_7e38cc05f6_Test {

    @Autowired
    private ProductController productController;

    @MockBean
    private ProductRepository productRepository;

    @Test
    public void testGetAllProducts_Success() {
        List<Product> products = new ArrayList<>();
        products.add(new Product());
        products.add(new Product());

        when(productRepository.findAll()).thenReturn(products);

        ResponseEntity<List<Product>> responseEntity = productController.getAllProducts();

        assertEquals(200, responseEntity.getStatusCodeValue());
        assertEquals(products, responseEntity.getBody());
    }

    @Test
    public void testGetAllProducts_NoProducts() {
        List<Product> products = new ArrayList<>();

        when(productRepository.findAll()).thenReturn(products);

        ResponseEntity<List<Product>> responseEntity = productController.getAllProducts();

        assertEquals(200, responseEntity.getStatusCodeValue());
        assertEquals(products, responseEntity.getBody());
    }

}
