// ********RoostGPT********
/*
Test generated by RoostGPT for test api-test using AI Type Claude AI and AI Model claude-3-opus-20240229

Test generated for /login_post for http method type POST in rest-assured framework

RoostTestHash=3122292ee3


*/

// ********RoostGPT********
