// Test generated by RoostGPT for test uploadfilespringboot using AI Type Vertex AI and AI Model code-bison

package com.bootexample4.products.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Product_setPrice_8f1e19b496_Test {

    @Test
    public void setPrice_validPrice_success() {
        // Arrange
        Product product = new Product();

        // Act
        product.setPrice(10.0);

        // Assert
        assertEquals(10.0, product.getPrice());
    }

    @Test
    public void setPrice_negativePrice_throwsIllegalArgumentException() {
        // Arrange
        Product product = new Product();

        // Act & Assert
        assertThrows(IllegalArgumentException.class, () -> product.setPrice(-10.0));
    }

}
