// Test generated by RoostGPT for test uploadfilespringboot using AI Type Vertex AI and AI Model code-bison

package com.bootexample4.products.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

public class Product_setId_04a8e16b7c_Test {

    @Test
    public void testSetId_ValidId_Success() {
        Product product = new Product();
        product.setId(1L);
        Assertions.assertEquals(1L, product.getId());
    }

    @Test
    public void testSetId_NullId_ThrowsIllegalArgumentException() {
        Product product = new Product();
        Assertions.assertThrows(IllegalArgumentException.class, () -> product.setId(null));
    }

    @Test
    public void testSetId_NegativeId_ThrowsIllegalArgumentException() {
        Product product = new Product();
        Assertions.assertThrows(IllegalArgumentException.class, () -> product.setId(-1L));
    }
}
