// Test generated by RoostGPT for test uploadfilespringboot using AI Type Vertex AI and AI Model code-bison

package com.bootexample4.products.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getName_8400ac6fb7_Test {

    @Test
    public void testGetName_whenNameIsSet_shouldReturnName() {
        // Arrange
        Product product = new Product();
        product.setName("Test Product");

        // Act
        String name = product.getName();

        // Assert
        assertEquals("Test Product", name);
    }

    @Test
    public void testGetName_whenNameIsNotSet_shouldReturnNull() {
        // Arrange
        Product product = new Product();

        // Act
        String name = product.getName();

        // Assert
        assertEquals(null, name);
    }
}
