// Test generated by RoostGPT for test uploadfilespringboot using AI Type Vertex AI and AI Model code-bison

package com.bootexample4.products.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_getPrice_d2cb73a47d_Test {

    @Test
    public void shouldReturnPrice() {
        Product product = new Product();
        product.setPrice(10.0);

        double expectedPrice = 10.0;
        double actualPrice = product.getPrice();

        assertEquals(expectedPrice, actualPrice);
    }

    @Test
    public void shouldReturnZeroForNullPrice() {
        Product product = new Product();

        double expectedPrice = 0.0;
        double actualPrice = product.getPrice();

        assertEquals(expectedPrice, actualPrice);
    }
}
