// Test generated by RoostGPT for test uploadfilespringboot using AI Type Vertex AI and AI Model code-bison

package com.bootexample4.products.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Product_setName_5d23a892d9_Test {

    @Test
    public void setName_ValidName_NameIsSet() {
        // Arrange
        Product product = new Product();

        // Act
        product.setName("Valid Name");

        // Assert
        assertEquals("Valid Name", product.getName());
    }

    @Test
    public void setName_EmptyName_NameNotSet() {
        // Arrange
        Product product = new Product();

        // Act
        product.setName("");

        // Assert
        assertEquals("", product.getName());
    }

    @Test
    public void setName_NullName_NameNotSet() {
        // Arrange
        Product product = new Product();

        // Act
        product.setName(null);

        // Assert
        assertEquals(null, product.getName());
    }
}
